name: custom_icons_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  font_awesome_flutter: ^8.10.0

  community_material_icon: ^5.4.55

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MyIcons
      fonts:
        - asset: assets/MyIcons.ttf